### PR TITLE
Tick version to 2.0.2, update run reqs, regenerate

### PR DESCRIPTION
**Pull request by pmlandwehr**
Update `promise` to 2.0.* since I'm doing a build of `graphene` and it needs the later version. Also regenerated.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
(ping @conda-forge/promise )

**Comment by pmlandwehr** [comment]
Another note for the @conda-forge/promise team here.

**Comment by pmlandwehr** [comment]
Another note for the @conda-forge/promise team here - any chance of getting this done? Need it for https://github.com/conda-forge/staged-recipes/pull/3013

**Comment by dfroger** [comment]
oh sorry, I've missed the PR mails... Can I add you to the maintainer list? Thanks.

**Comment by pmlandwehr** [comment]
Sure, no problem. I'm fine being added.

**Pull request merged**
