### PR TITLE
Correctly specify python version constraint for typing backport

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
When updating my py37 environment conda installed `typing`... because it's a dependency of `promise`.

As I understand it `typing` is a backport of the builtin `typing` module for `py<35` so it should never be installed in my py37 env.

In the `promise` library itself `typing` is only installed for `py<35`:
```python
    install_requires=[
        "typing>=3.6.4; python_version < '3.5'",
        "six"
    ],
```
https://github.com/syrusakbary/promise/blob/e2dc8f01fef03c7026c7fe07fbb3000c6f5f401f/setup.py#L56-L59

I think this is therefore a packaging bug in this repo which is fixed by this PR.

**Comment by dhirschfeld** [comment]
Installing the typing backport in my environment broke jupyterlab:
```python-traceback
  File "C:\Users\dhirschf\envs\dev\Lib\site-packages\typing.py", line 1003, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```
https://github.com/AnacondaRecipes/typing-feedstock/issues/2

**Comment by dhirschfeld** [comment]
ping @conda-forge/core 

I think this is a pretty nasty packaging bug (really a combination of bugs) so it would be good to at the very lest get his merged

I'm also all for pulling *any* `typing` package built for `py>=35` as IIUC they serve no purpose and can only (silently) break peoples enviroments.

https://gitter.im/conda-forge/conda-forge.github.io?at=5d65c1134b1189084e76e799#

**Comment by jjhelmus** [comment]
I am not a maintainer of this feedstock but this change looks good.  I'm going to merge.  If any of the maintainers feel this is in error please feed free to revert this change and ping me to move the newly build packages to the `broken` label.

**Comment by jjhelmus** [comment]
Thanks @dhirschfeld for this fix.

**Comment by dhirschfeld** [comment]
Thanks for the merge @jjhelmus!

**Pull request merged**
